--
-- PostgreSQL database dump
--

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ip_address character varying(50),
    new_value jsonb,
    old_value jsonb,
    target_id bigint,
    target_type character varying(50) NOT NULL,
    user_id bigint
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    id bigint NOT NULL,
    description text,
    name character varying(100) NOT NULL
);


--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facility; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facility (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    latitude double precision,
    longitude double precision,
    name character varying(100) NOT NULL,
    phone character varying(30),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT facility_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: facility_closed_date; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facility_closed_date (
    id bigint NOT NULL,
    closed_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(255),
    facility_id bigint NOT NULL
);


--
-- Name: facility_closed_date_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facility_closed_date ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facility_closed_date_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facility_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facility ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facility_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facility_manager; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facility_manager (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    facility_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: facility_manager_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facility_manager ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facility_manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facility_operation_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facility_operation_hours (
    id bigint NOT NULL,
    close_time time(0) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    day_of_week character varying(20) NOT NULL,
    is_closed boolean NOT NULL,
    open_time time(0) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    facility_id bigint NOT NULL,
    CONSTRAINT facility_operation_hours_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: facility_operation_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facility_operation_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facility_operation_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(64) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    id bigint NOT NULL,
    canceled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    end_time time(0) without time zone NOT NULL,
    people_count integer NOT NULL,
    reservation_date date NOT NULL,
    reservation_number character varying(50) NOT NULL,
    start_time time(0) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reservation_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'CANCELED'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    image_url character varying(500),
    is_active boolean NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    facility_id bigint NOT NULL
);


--
-- Name: room_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_equipment (
    id bigint NOT NULL,
    equipment_id bigint NOT NULL,
    room_id bigint NOT NULL
);


--
-- Name: room_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_operation_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_operation_hours (
    id bigint NOT NULL,
    close_time time(0) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    day_of_week character varying(20) NOT NULL,
    is_closed boolean NOT NULL,
    open_time time(0) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT room_operation_hours_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: room_operation_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room_operation_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_operation_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_reservation_method; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_reservation_method (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    external_url character varying(500),
    method_type character varying(20) NOT NULL,
    phone character varying(30),
    updated_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT room_reservation_method_method_type_check CHECK (((method_type)::text = ANY ((ARRAY['INTERNAL'::character varying, 'EXTERNAL'::character varying, 'PHONE'::character varying, 'VISIT'::character varying])::text[])))
);


--
-- Name: room_reservation_method_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room_reservation_method ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_reservation_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'FACILITY_ADMIN'::character varying, 'SYSTEM_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: facility_closed_date facility_closed_date_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_closed_date
    ADD CONSTRAINT facility_closed_date_pkey PRIMARY KEY (id);


--
-- Name: facility_manager facility_manager_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_manager
    ADD CONSTRAINT facility_manager_pkey PRIMARY KEY (id);


--
-- Name: facility_operation_hours facility_operation_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_operation_hours
    ADD CONSTRAINT facility_operation_hours_pkey PRIMARY KEY (id);


--
-- Name: facility facility_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility
    ADD CONSTRAINT facility_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--



--CREATE INDEX flyway_schema_history_s_idx
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_no_overlap; Type: CONSTRAINT; Schema: public; Owner: -
--
--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: room_equipment room_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_equipment
    ADD CONSTRAINT room_equipment_pkey PRIMARY KEY (id);


--
-- Name: room_operation_hours room_operation_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_operation_hours
    ADD CONSTRAINT room_operation_hours_pkey PRIMARY KEY (id);


--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- Name: room_reservation_method room_reservation_method_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_reservation_method
    ADD CONSTRAINT room_reservation_method_pkey PRIMARY KEY (id);


--
-- Name: equipment uk_equipment_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT uk_equipment_name UNIQUE (name);


--
-- Name: facility_closed_date uk_facility_closed_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_closed_date
    ADD CONSTRAINT uk_facility_closed_date UNIQUE (facility_id, closed_date);


--
-- Name: facility_manager uk_facility_manager_user_facility; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_manager
    ADD CONSTRAINT uk_facility_manager_user_facility UNIQUE (user_id, facility_id);


--
-- Name: facility_operation_hours uk_facility_operation_hours_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_operation_hours
    ADD CONSTRAINT uk_facility_operation_hours_day UNIQUE (facility_id, day_of_week);


--
-- Name: reservation uk_reservation_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT uk_reservation_number UNIQUE (reservation_number);


--
-- Name: room_equipment uk_room_equipment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_equipment
    ADD CONSTRAINT uk_room_equipment UNIQUE (room_id, equipment_id);


--
-- Name: room_operation_hours uk_room_operation_hours_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_operation_hours
    ADD CONSTRAINT uk_room_operation_hours_day UNIQUE (room_id, day_of_week);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: room_reservation_method ukk11f7svg2jgm86ptnqaqueye4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_reservation_method
    ADD CONSTRAINT ukk11f7svg2jgm86ptnqaqueye4 UNIQUE (room_id);


--
-- Name: refresh_token ukkdj16cltjxdksuyiosdhliveg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukkdj16cltjxdksuyiosdhliveg UNIQUE (token_hash);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--


--
-- Name: idx_audit_log_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_log_created_at ON public.audit_log USING btree (created_at);


--
-- Name: idx_audit_log_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_log_target ON public.audit_log USING btree (target_type, target_id);


--
-- Name: idx_refresh_token_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user ON public.refresh_token USING btree (user_id);


--
-- Name: idx_reservation_room_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_room_date ON public.reservation USING btree (room_id, reservation_date);


--
-- Name: facility_closed_date fk2kpr7916msxh6kovup6u3bk95; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_closed_date
    ADD CONSTRAINT fk2kpr7916msxh6kovup6u3bk95 FOREIGN KEY (facility_id) REFERENCES public.facility(id);


--
-- Name: facility_manager fk8d9wi51s5qt9irj7nnp9qstbc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_manager
    ADD CONSTRAINT fk8d9wi51s5qt9irj7nnp9qstbc FOREIGN KEY (facility_id) REFERENCES public.facility(id);


--
-- Name: room_reservation_method fkh1vx09n5kxve3af0fk6ag8hv3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_reservation_method
    ADD CONSTRAINT fkh1vx09n5kxve3af0fk6ag8hv3 FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: room_operation_hours fkj2eqwbs64igus7a2st4smyt0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_operation_hours
    ADD CONSTRAINT fkj2eqwbs64igus7a2st4smyt0x FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: audit_log fkk4alalwu62gj4tfbgfefll3tu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkk4alalwu62gj4tfbgfefll3tu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: room fkl25uqog8bljvpaeltumdv07sh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fkl25uqog8bljvpaeltumdv07sh FOREIGN KEY (facility_id) REFERENCES public.facility(id);


--
-- Name: facility_manager fkl4rk4b8tuq99hugex57brsyxo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_manager
    ADD CONSTRAINT fkl4rk4b8tuq99hugex57brsyxo FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reservation fkm8xumi0g23038cw32oiva2ymw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkm8xumi0g23038cw32oiva2ymw FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: facility_operation_hours fkq0pu4w27f4c05gd1frg1118c8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facility_operation_hours
    ADD CONSTRAINT fkq0pu4w27f4c05gd1frg1118c8 FOREIGN KEY (facility_id) REFERENCES public.facility(id);


--
-- Name: room_equipment fkqi32u6nxv9y6w769n87o958fj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_equipment
    ADD CONSTRAINT fkqi32u6nxv9y6w769n87o958fj FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: reservation fkrea93581tgkq61mdl13hehami; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: room_equipment fkrmdm2ihfq0rjieivqjmnty6hq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_equipment
    ADD CONSTRAINT fkrmdm2ihfq0rjieivqjmnty6hq FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- PostgreSQL database dump complete
--

